Web.header_content_type print_string Web.content_type_html;;
Web.header_break print_string ();;
print_string "<!DOCTYPE html>";;
print_string "<html lang=\"";;
Web.HTML.attribute_output_string `html5 print_string "en";;
print_string "\">";;
print_string "<body>";;
Web.HTML.text_output_string `html5 print_string "Hello, World!";;
print_string "</body>";;
print_string "</html>";;
print_newline ();;
